GET https://backgrupo5-production.up.railway.app/puntoReciclaje
########


POST https://backgrupo5-production.up.railway.app/usuario
Content-Type: application/json

{
 "email": "usuario12@gmail.com", 
 "contraseña": "Usuario12!", 
 "puntos":15 , 
 "codigoAmistad":"ABCD214311",
 "nombre": "Usuario12!"
}




###
POST https://backgrupo5-production.up.railway.app/objetivo
Content-Type: application/json

{
  "descripcion": "Recicla en 3 puntos de reciclaje", 
  "numObjetivo": 3,
  "puntosObtenibles": 300
}
###
POST https://backgrupo5-production.up.railway.app/ubicacion
Content-Type: application/json

{
  "latitud": 37.42197690113764, 
  "longitud": -122.08396590792049
}
###
POST https://backgrupo5-production.up.railway.app/codigoQR
Content-Type: application/json

{
  "contenido": "ecopoint3"
}
###
POST https://backgrupo5-production.up.railway.app/puntoReciclaje
Content-Type: application/json

{
 "idUbicacion": 3,
 "idCodigoQR": 3,
 "nombre": "GooglePlexPruebas", 
 "descripcion": "cerca de B40 y B43"
}
###
POST https://backgrupo5-production.up.railway.app/usuarioPuntoReciclaje
Content-Type: application/json

{
 "idUsuario": 1,
 "idPuntoReciclaje": 1
}
###
POST https://backgrupo5-production.up.railway.app/usuarioAmigo
Content-Type: application/json

{
 "idUsuario": 1,
 "idAmigo": 2
}
###

PUT https://backgrupo5-production.up.railway.app/puntoReciclaje
Content-Type: application/json

{
  "id": 1,
  "nombre":"Casa L"
}

###

GET https://backgrupo5-production.up.railway.app/puntoReciclaje/1
###

DELETE https://backgrupo5-production.up.railway.app/usuarioPuntoReciclaje/1

########
