GET http://localhost:3001/codigoQR
########

POST http://localhost:3001/puntoReciclaje
Content-Type: application/json

{
 "email": "test23463@gmail.com", 
 "contraseña": "1234", 
 "puntos": 0, 
 "codigoAmistad":"ABCD2143JK"
}
###
POST https://backgrupo5-production.up.railway.app/ubicacion
Content-Type: application/json

{
  "latitud": -12.00108253960971, 
  "longitud": -77.02039977116344
}
###
POST http://localhost:3001/codigoQR
Content-Type: application/json

{
  "contenido": "ecopoint1"
}
###
POST https://backgrupo5-production.up.railway.app/puntoReciclaje
Content-Type: application/json

{
 "idUbicacion": 2,
 "idCodigoQR": 2,
 "nombre": "CasaLPruebas", 
 "descripcion": "cerca del edificio x, contenedor azul"
}
###
POST https://backgrupo5-production.up.railway.app/usuarioPuntoReciclaje
Content-Type: application/json

{
 "idUsuario": 1,
 "idPuntoReciclaje": 1
}
###
POST https://backgrupo5-production.up.railway.app/usuarioAmigo
Content-Type: application/json

{
 "idUsuario": 1,
 "idAmigo": 2
}
###

PUT https://backgrupo5-production.up.railway.app/codigoQR
Content-Type: application/json

{
  "id": 2,
  "contenido":"ecopoint2"
}

###

GET https://backgrupo5-production.up.railway.app/puntoReciclaje/1
###

DELETE https://backgrupo5-production.up.railway.app/usuarioPuntoReciclaje/1

########
